trigger:
  branches:
    include:
      - main  # Define la rama que activará el pipeline

pool:
  name: casa  # Pool de agentes en EC2 (o cualquier pool que estés usando)

steps:
  - checkout: self  # Clonar el repositorio

  # Instalar Node.js en el agente si no está disponible
  - task: UseNode@1
    inputs:
      version: '16.x'  # Asegúrate de usar la misma versión de Node.js que requiere tu proyecto

  # Instalar las dependencias necesarias
  - script: |
      sudo apt-get update
      sudo apt-get install -y xvfb libgtk-3-0 libx11-xcb1 libxtst6 libxss1 libatk1.0-0
    displayName: 'Instalar dependencias de Cypress'

  # Instalar las dependencias del proyecto (incluyendo Cypress)
  - script: |
      npm install
    displayName: 'Instalar dependencias'

  # Ejecutar las pruebas de Cypress usando npx
  - script: |
      npx cypress run
    displayName: 'Ejecutar pruebas de Cypress'

  # Opción de guardar reportes si es necesario
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/cypress/results/*.xml'
      testRunTitle: 'Resultados de Cypress'
      mergeTestResults: true